# Generated by Django 5.2.5 on 2025-09-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
